# Generated by Django 4.2.15 on 2025-05-15 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account_table",
            fields=[
                ("account_id", models.AutoField(primary_key=True, serialize=False)),
                ("account_balance", models.BigIntegerField(default=0)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Savings", "Savings"),
                            ("Current", "Current"),
                            ("Fixed Deposit", "Fixed Deposit"),
                            ("Domiciliary", "Domiciliary"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(default="0000000000", max_length=10, unique=True),
                ),
                ("account_pin", models.CharField(default="0000", max_length=4)),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Retired", "Retired"),
                            ("Suspended", "Suspended"),
                            ("Freeze", "Freeze"),
                            ("On Leave", "On Leave"),
                            ("Dormant", "Dormant"),
                        ],
                        default="Active",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction_table",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("transaction_type", models.CharField(max_length=20)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("transaction_amount", models.BigIntegerField()),
                ("recepient_phone_number", models.CharField(max_length=11, null=True)),
                (
                    "recepient_bank_name",
                    models.CharField(max_length=20, null=True, unique=True),
                ),
                (
                    "recepient_account_number",
                    models.CharField(max_length=10, null=True),
                ),
                ("sender_bank_name", models.CharField(max_length=10, null=True)),
                (
                    "bill_type",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("PHCN", "PHCN"),
                            ("GOTV", "GOTV"),
                            ("DSTV", "DSTV"),
                            ("Water Bill", "Water Bill"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "mobile_networks",
                    models.CharField(
                        choices=[
                            ("", "Select"),
                            ("MTN", "MTN"),
                            ("GLO", "GLO"),
                            ("AIRTEL", "AIRTEL"),
                            ("ETISALAT", "ETISALAT"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactionapp.account_table",
                    ),
                ),
                (
                    "sender_account_number",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to="transactionapp.account_table",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill_payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_type",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("PHCN", "PHCN"),
                            ("GOTV", "GOTV"),
                            ("DSTV", "DSTV"),
                            ("Star Times", "Star Times"),
                            ("Water Bill", "Water Bill"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.BigIntegerField()),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("reference", models.CharField(max_length=50, unique=True)),
                (
                    "meter_number",
                    models.CharField(max_length=20, null=True, unique=True),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("New Request", "New Request"),
                            ("Renewal", "Renewal"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "months_of_sub",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "decoder_number",
                    models.CharField(max_length=20, null=True, unique=True),
                ),
                (
                    "account_number",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_payments_by_account",
                        to="transactionapp.account_table",
                    ),
                ),
                (
                    "account_pin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_payments_by_pin",
                        to="transactionapp.account_table",
                    ),
                ),
            ],
        ),
    ]
