# Generated by Django 4.2.15 on 2025-05-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactionapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill_payment",
            name="account_pin",
        ),
        migrations.AlterField(
            model_name="account_table",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("Savings", "Savings"),
                    ("Current", "Current"),
                    ("Fixed Deposit", "Fixed Deposit"),
                ],
                max_length=20,
            ),
        ),
    ]
