# Generated by Django 4.2.15 on 2025-06-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactionapp", "0002_remove_bill_payment_account_pin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction_table",
            name="recepient_bank_name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
