# Generated by Django 4.2.15 on 2025-06-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactionapp", "0003_alter_transaction_table_recepient_bank_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill_payment",
            name="cable_type",
            field=models.CharField(
                choices=[
                    ("PHCN", "PHCN"),
                    ("IKEJA Electricity", "IKEJA Electricity"),
                    ("Abuja Electricity", "Abuja Electricity"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bill_payment",
            name="electricity_type",
            field=models.CharField(
                choices=[
                    ("PHCN", "PHCN"),
                    ("IKEJA Electricity", "IKEJA Electricity"),
                    ("Abuja Electricity", "Abuja Electricity"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bill_payment",
            name="bill_type",
            field=models.CharField(
                choices=[
                    ("Electricity", "Electricity"),
                    ("Cable", "Cable"),
                    ("Water Bill", "Water Bill"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction_table",
            name="bill_type",
            field=models.CharField(
                choices=[
                    ("Electricity", "Electricity"),
                    ("Cable", "Cable"),
                    ("Water Bill", "Water Bill"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction_table",
            name="mobile_networks",
            field=models.CharField(
                choices=[
                    ("MTN", "MTN"),
                    ("GLO", "GLO"),
                    ("AIRTEL", "AIRTEL"),
                    ("ETISALAT", "ETISALAT"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
