# Generated by Django 4.2.15 on 2025-06-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactionapp", "0004_bill_payment_cable_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill_payment",
            name="water_service_number",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="bill_payment",
            name="cable_type",
            field=models.CharField(
                choices=[
                    ("DSTV", "DSTV"),
                    ("GOTV", "GOTV"),
                    ("Startimes", "Startimes"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
