# Generated by Django 4.2.15 on 2025-06-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactionapp", "0005_bill_payment_water_service_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill_payment",
            name="water_bill_type",
            field=models.CharField(
                choices=[
                    ("Nigeria Water Cooperation", "Nigeria Water Cooperation"),
                    ("General Waters", "General Waters"),
                    ("Lagos Inc", "Lagos Inc"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
