# Generated by Django 4.2.15 on 2025-06-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactionapp", "0006_bill_payment_water_bill_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill_payment",
            name="decoder_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="bill_payment",
            name="meter_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="bill_payment",
            name="water_service_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
