# Generated by Django 4.2.15 on 2025-06-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactionapp", "0007_alter_bill_payment_decoder_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill_payment",
            name="cable_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DSTV", "DSTV"),
                    ("GOTV", "GOTV"),
                    ("Startimes", "Startimes"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bill_payment",
            name="decoder_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="bill_payment",
            name="electricity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PHCN", "PHCN"),
                    ("IKEJA Electricity", "IKEJA Electricity"),
                    ("Abuja Electricity", "Abuja Electricity"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bill_payment",
            name="meter_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="bill_payment",
            name="months_of_sub",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bill_payment",
            name="request_type",
            field=models.CharField(
                blank=True,
                choices=[("New Request", "New Request"), ("Renewal", "Renewal")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bill_payment",
            name="water_bill_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Nigeria Water Cooperation", "Nigeria Water Cooperation"),
                    ("General Waters", "General Waters"),
                    ("Lagos Inc", "Lagos Inc"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
