# Generated by Django 4.2.15 on 2025-06-11 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactionapp", "0008_alter_bill_payment_cable_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill_payment",
            name="account_balance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bill_payments_by_account_balance",
                to="transactionapp.account_table",
            ),
        ),
        migrations.AddField(
            model_name="bill_payment",
            name="account_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bill_payments_by_account_type",
                to="transactionapp.account_table",
            ),
        ),
    ]
