# Generated by Django 4.2.15 on 2025-06-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactionapp", "0009_bill_payment_account_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill_payment",
            name="account_balance",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="bill_payment",
            name="account_type",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
