# Generated by Django 4.2.15 on 2025-06-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactionapp", "0010_alter_bill_payment_account_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account_table",
            name="account_pin",
            field=models.CharField(default="0000", max_length=128),
        ),
    ]
