# Generated by Django 4.2.15 on 2025-06-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactionapp", "0011_alter_account_table_account_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill_payment",
            name="account_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
