# Generated by Django 4.2.15 on 2025-06-12 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactionapp", "0012_alter_bill_payment_account_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction_table",
            name="account_type_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_account_type",
                to="transactionapp.account_table",
            ),
        ),
        migrations.AlterField(
            model_name="bill_payment",
            name="bill_type",
            field=models.CharField(
                choices=[
                    ("Electricity", "Electricity"),
                    ("Cable", "Cable"),
                    ("Water", "Water"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction_table",
            name="bill_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_bill_type",
                to="transactionapp.bill_payment",
            ),
        ),
    ]
